### ISSUE TITLE
Headless LAN server

### ISSUE THREAD

**Issue by Villantiqua** [drazdra/ollama-chats#1]
Hi, 
I like this🙂. What do I have to change in the index.html if I want to access Ollama-chats from any pc on the local network, knowing the static ip address of my local server on which Ollama and Apache is running?

**Comment by Villantiqua** [comment]
Thanks for the fast reply. Yes, ollama and Apache are on the same server. Indeed, your website came up on a pc in the local network, but I got an error, not being able to connect to Ollama server or something like that. I’ll investigate later. Thanks for now, and I will let you know the final outcome when I have time to test.Sent from my iPadOn 27 Mar 2024, at 16:09, drazdra ***@***.***> wrote:﻿
you will need to change an ollama environment setting ("origin" or sth like that), check ollama faq, it was there. my script by default tries to connect to localhost, but if it can't, it will automatically ask you to enter another address, so you can use the ip address of your ollama server.

**Comment by drazdra** [comment]
ah right, it's client side, so request will have your ip. ollama blocks access from anything but localhost. refer to my first part of the message and configure ollama to allow connections from other ips.

**Comment by Villantiqua** [comment]
I found the Ollama FAQ. It’s all there. Thank you for pointing in the right direction. I am confident I will manage later.Sent from my iPadOn 27 Mar 2024, at 16:09, drazdra ***@***.***> wrote:﻿
you will need to change an ollama environment setting ("origin" or sth like that), check ollama faq, it was there. my script by default tries to connect to localhost, but if it can't, it will automatically ask you to enter another address, so you can use the ip address of your ollama server.

**Comment by drazdra** [comment]
done
