### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by snosluoc** [drazdra/ollama-chats#10]
I'm running Ollama in a Docker image on a windows 11 home pc.
I went the easy way for testing, adding the "environment variables" - "OLLAMA_ORIGINS" - "*".
When I try to connect I receive "Cannot convert undefined or null to object"
I am hitting Ollama because if the change the port or address I receive this message "Failed to fetch"

Very new to all this, sorry if it's something stupid I'm over looking.

**Comment by drazdra** [comment]
it's hard to guess with that little info. if you run it in docker on a different ip than localhost you will also need to set OLLAMA_HOST variable to 0.0.0.0
that would allow connections from any IPs.
not sure if it's the easy way, tho.

**Comment by snosluoc** [comment]
Sorry, totally my fault. I got it working once I pointed it to the correct port...
