### ISSUE TITLE
it will be so cool if there is a daytime theme to switch 

### ISSUE THREAD

**Issue by farwish** [drazdra/ollama-chats#4]
maybe someone can contribute, after reading the code, as daily using tool.  💝

**Comment by drazdra** [comment]
will inverted colors be enough for you? it's light and perfectly readable then but it doesn't look like a piece of art :). is it ok?

**Comment by farwish** [comment]
> will inverted colors be enough for you? it's light and perfectly readable then but it doesn't look like a piece of art :). is it ok?

probably enough.  ok, perfect.

**Comment by drazdra** [comment]
i will add it in the next version. you can do it yourself for now by running in console

document.getElementsByTagName('HTML')[0].style.filter='invert(100%) hue-rotate(180deg)'

or add into the index.html the rule into the <style> definition:

html {
 filter: invert(100%) hue-rotate(180deg)
}

**Comment by farwish** [comment]
> i will add it in the next version. you can do it yourself for now by running in console
> 
> document.getElementsByTagName('HTML')[0].style.filter='invert(100%) hue-rotate(180deg)'
> 
> or add into the index.html the rule into the <style> definition:
> 
> html { filter: invert(100%) hue-rotate(180deg) }

command in console worked and feel good.

**Comment by drazdra** [comment]
new version has day theme
