### ISSUE TITLE
3 clicks away from a git hub page!

### ISSUE THREAD

**Issue by mrdjohnson** [drazdra/ollama-chats#5]
👋 

Because this is just a webpage it can easily be a github page without users needing to set up their own server, and they can access it directly from your github! 

Even if its not something you'd use personally, it does open up the door for your users to be able to check out your page super quickly :) 

I forked the repo and set the main branch to be the git hub page and its running just fine: 
https://mrdjohnson.github.io/ollama-chats/
<img width="1593" alt="image" src="https://github.com/drazdra/ollama-chats/assets/6767910/f8cf4b07-6100-458b-9831-0af30f9c604b">

Caveats, like with all git hub page ollama apps, your users would need to run ollama from the command line 
`OLLAMA_ORIGINS=*.github.io ollama serve` this works for mac users (also could just set the origin to * 
`$env:OLLAMA_ORIGINS="https://%2A.github.io/"; ollama serve` this works for powershell users

I used * but you can actually use `OLLAMA_ORIGINS=drazdra.github.io ollama serve` specifically

To have this ability goto the Pages section under the settings tab:
<img width="1271" alt="image" src="https://github.com/drazdra/ollama-chats/assets/6767910/c05093f6-24ec-4c50-91c9-935c5a5e1886">

Just for consideration! 🤷‍♂️

**Comment by drazdra** [comment]
i've updated the readme with instruction on how to configure the script on ubuntu and on windows to open it from disk with no web-server. Also, i've added github page as you requested (don't know what for) :).

**Comment by mrdjohnson** [comment]
It's for people to have 1 click access to your page!

Also if you go edit the project description there is a button to include the GitHub page.

Anyway, keep it up with the project!
