### ISSUE TITLE
Loading per-AI images

### ISSUE THREAD

**Issue by kragger** [drazdra/ollama-chats#7]
A JS error is thrown when attempting to set the background image for an AI.
Settings -> Design Features -> Background image
A dialog appears however once selecting an image and applying it the background does not change. The console reports the error:
this.$parent.loadFile is not a function

Notably this same routine does function as expected when attaching an image to the chat log so it is seemingly a scope issue.

I can also base64 encode an image manually and paste it into the saved log which then causes it to appear as expected.

I appreciate the ability to have separate backgrounds per AI to help assist in ensuring I'm conversing with the appropriate entity.

**Comment by drazdra** [comment]
i am lost, there is only one way to attach the image, which is to go settings, design features, background image - choose a file and load it, then background changes. at least i just checked it here, it worked. what do you mean with "Notably this same routine does function as expected when attaching an image to the chat log so it is seemingly a scope issue." ? do you call it from the console?

could you tell me your browser and the file type you are loading?

**Comment by kragger** [comment]
Sorry I was just watching the code when I tried adding an image to the chat.  So for the AI in the settings here:

￼
Clicking Background Image and selecting a picture results in this error:
￼
Using the +image button with the prompt window appears to take the same code path but attaches the chosen image:
 ￼

**Comment by drazdra** [comment]
image under the prompt is not for background. it adds image to the chat log, to make vision enabled models to see what you show them.

**Comment by drazdra** [comment]
i've added a small patch, as i dont use that version locally, please update from github and tell me if it works now for you. if not, i will look into getting that version locally and checking myself.

**Comment by kragger** [comment]
That works perfectly, thanks!
